tweets/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('tweets.views',
    url(r'^/?$', 'timeline', name='timeline'),
    url(r'^public/$', 'publicline', name='publicline'),
    url(r'^(?P<username>\w+)/$', 'userline', name='userline'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
    url('^auth/', include('users.urls')),
    url('', include('tweets.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

users/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('users.views',
    url('^login/$', 'login', name='login'),
    url('^logout/$', 'logout', name='logout'),
    url(r'^find-friends/$', 'find_friends', name='find_friends'),
    url(r'^modify-friend/$', 'modify_friend', name='modify_friend'),
)

users/models.py
# Nope, we're using Riak :)

tweets/forms.py
from django import forms

class TweetForm(forms.Form):
    body = forms.CharField(max_length=140)

users/forms.py
import uuid

from django import forms

import riakapi

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput(render_value=False))
    
    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = riakapi.get_user_by_username(username)
        except riakapi.DatabaseError:
            raise forms.ValidationError(u'Invalid username and/or password')
        if user.get('password') != password:
            raise forms.ValidationError(u'Invalid username and/or password')
        return self.cleaned_data

    def get_username(self):
        return self.cleaned_data['username']
    

class RegistrationForm(forms.Form):
    username = forms.RegexField(regex=r'^\w+$', max_length=30)
    password1 = forms.CharField(widget=forms.PasswordInput(render_value=False))
    password2 = forms.CharField(widget=forms.PasswordInput(render_value=False))
    
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            riakapi.get_user_by_username(username)
            raise forms.ValidationError(u'Username is already taken')
        except riakapi.DatabaseError:
            pass
        return username
    
    def clean(self):
        if ('password1' in self.cleaned_data and 'password2' in 
            self.cleaned_data):
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 != password2:
                raise forms.ValidationError(
                    u'You must type the same password each time')
        return self.cleaned_data
    
    def save(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password1']
        riakapi.save_user(username, {
            'password': password,
        })
        return username

tweets/views.py
import uuid

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse

from tweets.forms import TweetForm

import riakapi

NUM_PER_PAGE = 20

def timeline(request):
    form = TweetForm(request.POST or None)
    if request.user['is_authenticated'] and form.is_valid():
        tweet_id = str(uuid.uuid1())
        riakapi.save_tweet(tweet_id, request.session['username'], {
            'username': request.session['username'],
            'body': form.cleaned_data['body'],
        })
        return HttpResponseRedirect(reverse('timeline'))
    start = request.GET.get('start')
    if request.user['is_authenticated']:
        tweets,next = riakapi.get_timeline(request.session['username'],
            start=start, limit=NUM_PER_PAGE)
    else:
        tweets,next = riakapi.get_publicline(start=start, limit=NUM_PER_PAGE)
    context = {
        'form': form,
        'tweets': tweets,
        'next': next,
    }
    return render_to_response('tweets/timeline.html', context,
        context_instance=RequestContext(request))

def publicline(request):
    start = request.GET.get('start')
    tweets,next = riakapi.get_publicline(start=start, limit=NUM_PER_PAGE)
    context = {
        'tweets': tweets,
        'next': next,
    }
    return render_to_response('tweets/publicline.html', context,
        context_instance=RequestContext(request))

def userline(request, username=None):
    try:
        user = riakapi.get_user_by_username(username)
    except riakapi.DatabaseError:
        raise Http404
    
    # Query for the friend ids
    friend_usernames = []
    if request.user['is_authenticated']:
        friend_usernames = riakapi.get_friend_usernames(username) + [username]
    
    # Add a property on the user to indicate whether the currently logged-in
    # user is friends with the user
    user['friend'] = username in friend_usernames
    
    start = request.GET.get('start')
    tweets,next = riakapi.get_userline(username, start=start,
        limit=NUM_PER_PAGE)
    context = {
        'user': user,
        'username': username,
        'tweets': tweets,
        'next': next,
        'friend_usernames': friend_usernames,
    }
    return render_to_response('tweets/userline.html', context,
        context_instance=RequestContext(request))

users/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect

from users.forms import LoginForm, RegistrationForm

import riakapi

def login(request):
    login_form = LoginForm()
    register_form = RegistrationForm()
    next = request.REQUEST.get('next')
    if 'kind' in request.POST:
        if request.POST['kind'] == 'login':
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                username = login_form.get_username()
                request.session['username'] = username
                if next:
                    return HttpResponseRedirect(next)
                return HttpResponseRedirect('/')
        elif request.POST['kind'] == 'register':
            register_form = RegistrationForm(request.POST)
            if register_form.is_valid():
                username = register_form.save()
                request.session['username'] = username
                if next:
                    return HttpResponseRedirect(next)
                return HttpResponseRedirect('/')
    context = {
        'login_form': login_form,
        'register_form': register_form,
        'next': next,
    }
    return render_to_response('users/login.html', context,
        context_instance=RequestContext(request))

def logout(request):
    request.session.pop('username', None)
    return render_to_response('users/logout.html', {},
        context_instance=RequestContext(request))

def find_friends(request):
    friend_usernames = []
    if request.user['is_authenticated']:
        friend_usernames = riakapi.get_friend_usernames(
            request.session['username']) + [request.session['username']]
    q = request.GET.get('q')
    result = None
    searched = False
    if q is not None:
        searched = True
        try:
            result = riakapi.get_user_by_username(q)
            result['friend'] = q in friend_usernames
        except riakapi.DatabaseError:
            pass
    context = {
        'q': q,
        'result': result,
        'searched': searched,
        'friend_usernames': friend_usernames,
    }
    return render_to_response('users/add_friends.html', context,
        context_instance=RequestContext(request))

def modify_friend(request):
    next = request.REQUEST.get('next')
    added = False
    removed = False
    if request.user['is_authenticated']:
        if 'add-friend' in request.POST:
            riakapi.add_friends(
                request.session['username'],
                [request.POST['add-friend']]
            )
            added = True
        if 'remove-friend' in request.POST:
            riakapi.remove_friends(
                request.session['username'],
                [request.POST['remove-friend']]
            )
            removed = True
    if next:
        return HttpResponseRedirect(next)
    context = {
        'added': added,
        'removed': removed,
    }
    return render_to_response('users/modify_friend.html', context,
        context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>{% block title %}Tweeak{% endblock %}</title>
		<meta name="description" content="{% block description %}Tweeak is an example Twitter implementation, using Cassandra{% endblock %}" />
		<link href="{{ MEDIA_URL }}css/reset.css" rel="stylesheet" type="text/css" media="screen,projection" />
		<link href="{{ MEDIA_URL }}css/960.css" rel="stylesheet" type="text/css" media="screen,projection" />
		<link href="{{ MEDIA_URL }}css/text.css" rel="stylesheet" type="text/css" media="screen,projection" />
		<link href="{{ MEDIA_URL }}css/screen.css" rel="stylesheet" type="text/css" media="screen,projection" />
	</head>
	<body>
	    <div class="container_12 clearfix">
	        <div id="header">
	            <div id="logo" class="grid_7">
	                <a href="/">Tweeak</a>
	            </div>
        	    <ul id="nav" class="grid_5">
        	        <li><a href="{% url timeline %}">Home</a></li>
        	        <li><a href="{% url publicline %}">Public</a></li>
        	        <li><a href="{% url find_friends %}">Find Friends</a></li>
        	        {% if request.user.is_authenticated %}
        	            <li><a href="{% url logout %}">Sign out of {{ request.session.username }}</a></li>
        	        {% else %}
        	            <li><a href="{% url login %}">Login</a></li>
        	        {% endif %}
        	    </ul>
    	    </div>
    	    <div class="clear"></div>
    	    {% block content %}
    	    {% endblock %}
    	    <div id="sidebar" class="grid_3 omega">
                <p>
                    Tweeak is an example project, created to learn and demonstrate how to use
                    Riak.  Running the project will present a website that has similar
                    functionality to Twitter.
                </p>
                <p>
                    View the code for this site <a href="http://github.com/ericflo/tweeak">on GitHub</a>
                </p>
                {% block sidebar %}
                {% endblock %}
            </div>
	    </div>
	</body>
</html>

templates/tweets/publicline.html
{% extends "base.html" %}

{% block title %}Public Timeline - {{ block.super }}{% endblock %}

{% block content %}
    <h2 class="grid_4 suffix_5">Public Timeline</h2>
    <ul id="timeline" class="grid_9 alpha">
        {% for tweet in tweets %}
            <li>
                <a href="{% url userline tweet.username %}" class="username">{{ tweet.username }}</a>
                <span class="body">{{ tweet.body|urlize }}</span>
            </li>
        {% empty %}
            <li>There are no tweets yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>
{% endblock %}

templates/tweets/timeline.html
{% extends "base.html" %}

{% block title %}My Timeline - {{ block.super }}{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <form method="POST" id="poster">
            <div class="grid_9 alpha">
                <textarea maxlength="140" name="body" type="text" id="id_body"></textarea>
            </div>
            <input type="submit" value="Post Tweet" class="grid_3 omega">
            <div class="clear"></div>
        </form>
    {% else %}
        <h2 class="grid_4 suffix_5">Public Timeline</h2>
    {% endif %}
    <ul id="timeline" class="grid_9 alpha">
        {% for tweet in tweets %}
            <li>
                <a href="{% url userline tweet.username %}" class="username">{{ tweet.username }}</a>
                <span class="body">{{ tweet.body|urlize }}</span>
            </li>
        {% empty %}
            <li>There are no tweets yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block sidebar %}
    {% if not request.user.is_authenticated %}
        <a href="{% url login %}">Log in to post a tweet</a>
    {% endif %}
{% endblock %}

templates/tweets/userline.html
{% extends "base.html" %}

{% block title %}{{ username }} - {{ block.super }}{% endblock %}

{% block content %}
    <h2 class="grid_4 suffix_5">{{ username }}&rsquo;s Timeline</h2>
    <ul id="timeline" class="grid_9 alpha">
        {% for tweet in tweets %}
            <li>
                <a href="{% url userline tweet.username %}" class="username">{{ tweet.username }}</a>
                <span class="body">{{ tweet.body|urlize }}</span>
            </li>
        {% empty %}
            <li>There are no tweets yet.  Make sure to post one!</li>
        {% endfor %}
        {% if next %}
            <li class="more"><a href="?start={{ next }}">More</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block sidebar %}
    {% if request.user.is_authenticated %}
        {% ifnotequal request.user.id user.id %}
            <form method="POST" action="{% url modify_friend %}?next={{ request.path }}">
                <input type="hidden" name="{% if user.friend %}remove{% else %}add{% endif %}-friend" value="{{ user.id }}" />
                <input type="submit" value="{% if user.friend %}Remove{% else %}Add{% endif %} Friend" />
            </form>
        {% endifnotequal %}
    {% else %}
        <a href="{% url login %}?next={{ request.path }}&q={{ q }}">
            Login to add {{ username }} as a friend
        </a>
    {% endif %}
{% endblock %}

templates/users/add_friends.html
{% extends "base.html" %}

{% block title %}Find and Add Friends - {{ block.super }}{% endblock %}

{% block content %}
    <h2 class="grid_4 suffix_5">Add Friends</h2>
    <div class="grid_9 alpha">
        <form method="GET" class="grid_6">
            <input type="text" name="q" value="{% if q %}{{ q }}{% endif %}" />
            <input type="submit" value="Search" />
        </form>
        <div class="grid_6">
            {% if searched %}
                {% if result %}
                    <p>Hooray, your friend {{ q }} is on the site!</p>
                    {% if request.user.is_authenticated %}
                        {% ifnotequal request.session.username q %}
                            <form method="POST" action="{% url modify_friend %}?next={{ request.path }}{% if q %}&amp;q={{ q }}{% endif %}">
                                <input type="hidden" name="{% if result.friend %}remove{% else %}add{% endif %}-friend" value="{{ q }}" />
                                <input type="submit" value="{% if result.friend %}Remove{% else %}Add{% endif %} Friend" />
                            </form>
                        {% endifnotequal %}
                    {% else %}
                        <a href="{% url login %}?next={{ request.path }}&amp;q={{ q }}">
                            Login to add {{ q }} as a friend
                        </a>
                    {% endif %}
                {% else %}
                    <p>There was nobody with username {{ q }}</p>
                {% endif %}
            {% else %}
                <p>Enter a username above to see if they are on the site!</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% block title %}Login - {{ block.super }}{% endblock %}

{% block content %}
    <div class="grid_9 alpha">
        <div class="auth grid_4 prefix_1 alpha" id="signin">
            <h2 class="grid_4">Sign In</h2>
            <form method="POST">
                <ul>
                    {{ login_form.as_ul }}
                </ul>
                <input type="hidden" name="kind" value="login" />
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                <input type="submit" value="Sign In" />
            </form>
        </div>
    
        <div class="auth grid_4 omega" id="signup">
            <h2 class="grid_4">Sign Up</h2>
            <form method="POST">
                <ul>
                    {{ register_form.as_ul }}
                </ul>
                <input type="hidden" name="kind" value="register" />
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                <input type="submit" value="Sign Up" />
            </form>
        </div>
    </div>
{% endblock %}

templates/users/logout.html
{% extends "base.html" %}

{% block title %}Logged Out - {{ block.super }}{% endblock %}

{% block content %}
    <div class="grid_9 alpha">
        <h2 class="grid_4 suffix_5">You have been logged out</h2>
        <p class="grid_6">Thanks for using Tweeak.</p>
    </div>
{% endblock %}

templates/users/modify_friend.html
{% extends "base.html" %}

{% block title %}Friend Changed - {{ block.super }}{% endblock %}

{% block content %}
    <div class="grid_9 alpha">
        <h2>Friend successfully {% if added %}Added{% else %}Removed{% endif %}</h2>
        <p>The user has been {% if added %}added to{% else %}removed from{% endif %} your friends list.</p>
    </div>
{% endblock %}